language: java

addons:
  postgresql: "9.6"

cache:
  directories:
  - $HOME/.m2

before_script:
  - psql -c "CREATE DATABASE object_store_test;" -U postgres
  - psql -f src/test/resources/create-test-users.sql object_store_test -U postgres

script: 
  - mvn verify -Dspring.datasource.url=jdbc:postgresql://localhost/object_store_test?currentSchema=object_store -Dspring.datasource.username=web_user -Dspring.datasource.password=test -Dspring.liquibase.user=migration_user -Dspring.liquibase.password=test checkstyle:check com.github.spotbugs:spotbugs-maven-plugin:check jacoco:check
 
jdk:
  - openjdk8
  - openjdk10
  - openjdk11
